Let the logger format the message lazily.
kapicorp/kapitan pull request #700
Opened 2021-03-02 15:20 UTC by Jean-Daniel

Using `format()` for logger is discouraged as it forces the message to format the message even when log are disabled.

Moreover, the `.format` vs `%s` is used inconsistently all over the codebase.
Switching all usages to the logger builtin formatting make the code more consistent.

## Proposed Changes

  - convert all usage of `format()` to format logging message to use the builtin logging formatter instead.

2021-03-02 18:53 UTC, ademariag commented
Thank you for yet another contribution @Jean-Daniel . Join our slack channel on kubernetes slack (https://slack.k8s.io/) if you can!

2021-03-04 15:37 UTC, ramaro commented on kapitan/resources.py
> +                    logger.debug(f"import_str: %s found in search_path: %s", import_str, path)
need to remove the f-string here as well

2021-03-04 15:42 UTC, ramaro requested changes
Looks good, thanks @Jean-Daniel - just one tiny comment to change.

2021-03-05 14:27 UTC, ramaro approved these changes

2021-03-05 14:28 UTC, merged