Fix kadet serialization to yaml not preserving key orders (#835)
kapicorp/kapitan pull request #836
Opened 2022-04-24 11:36 UTC by Marvisak

Fixes issue #835 

## Proposed Changes

  - Makes kadet not sort keys when dumping into YAML, this fixes inconsistencies with JSON and makes the result much easier to read if it was loaded with `.update_root` before

2022-10-30 22:19 UTC, ramaro commented
@Marvisak apologies, I completely missed this. I think however that this should be a behavior controlled via a flag, because sorting keys is useful (e.g. people will rely on it (I do!)

2023-04-20 14:24 UTC, MatteoVoges requested changes
Hey @Marvisak , thank you for your contribution. It makes sense to have the `sort_keys` property disabled, like stated in #835 . Could you remove the changes in the examples and the compiled output or is there a reason for that? I think if you rebase your branch, we are ready to merge!

2023-04-20 19:28 UTC, Marvisak commented on examples/kubernetes/compiled/minikube-nginx-kadet/manifests/nginx_deployment.yml
I didn't make the changes, I just ran the tests and it ended up like that.

2023-04-21 08:10 UTC, MatteoVoges commented on examples/kubernetes/compiled/minikube-nginx-kadet/manifests/nginx_deployment.yml
Alright, i think it just needs a rebase then

2024-09-01 17:38 UTC, closed without merging