Conditional dependency download and compile
kapicorp/kapitan pull request #842
Opened 2022-07-01 07:34 UTC by megian

## Proposed Changes

Depending on features turned on or off, this allows to individual
download or skip certain dependencies and compile them just if they
turned on.

The default behavior of download and compile everything doesn't
change with it. Existing use cases must not have any behavior changes.

2022-07-01 07:35 UTC, megian commented
Documentation and tests are pending.

2022-07-01 07:51 UTC, simu commented
The broader context here: Conditional dependency fetching and compile steps would be very helpful for us in Project Syn, e.g. for stuff like https://github.com/projectsyn/component-keycloak/pull/135/commits/95d3bc6029bfc7f2bf518ec8ea07ba5dbd0347ee where we now have a postprocessing step to delete the rendered Postgres helm chart if Keycloak is configured to use an external database. @ramaro @ademariag what do you think?

2022-07-05 10:03 UTC, ramaro commented
@megian @simu how would this valued be managed? Would it be an external process (e.g. projectsyn) updating the value of `condition`? Also thoughts on renaming `condition` into `skip` ? (I find in it more obvious)

2022-07-06 05:55 UTC, megian commented
Initially inspired by the helm chart dependency [condition](https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags) flag `condition: somechart.enabled`. As Simon @simu already mentioned, this would result in a inverse logic.

In a real example with `condition`:
```
=_enable_pg_chart:
  builtin: true         # PostgreSQL Helm Chart has to be rendered
  external: false    # PostgreSQL Helm Chart has not to be rendered

parameters:
  kapitan:
    dependencies:
      - type: helm
        condition: ${keycloak:_enable_pg_chart:${keycloak:database:provider}}
```
Compared to `skip`:
```
=_skip_pg_chart:
  builtin: false      # PostgreSQL Helm Chart has to be rendered
  external: true    # PostgreSQL Helm Chart has not to be rendered

parameters:
  kapitan:
    dependencies:
      - type: helm
        skip: ${keycloak:_skip_pg_chart:${keycloak:database:provider}}
```
For my understanding `_enable_pg_chart` condition on true makes it obvious it is executed (Feature enabled, feature is downloaded and compiled). `_skip_pg_chart` causes me questions while reading the code, when should I skip what. This will even become more complex, when multiple features have to be skipped in a inverse logic.

Summarized: As set skip manually to `yes` is not really a use case, except of debugging, which we can ignore here I think. The main use case is to switch features on or off. Usually it is turned on by default for the reason as it is there (if it wouldn't, it would got dropped). If the variable is called `condition` or `enabled` doesn't matter. I still think that from the main usage perspective a positive logic makes sense.

2023-07-26 09:01 UTC, MatteoVoges requested changes
Do you want to only be able to skip dependencies or do you want this behavior for entire compile definitions as well?

2023-07-26 09:01 UTC, MatteoVoges commented on kapitan/dependency_manager/base.py
> +                    logger.warning(
please change to `debug`, to make it less verbose

2024-09-01 17:38 UTC, closed without merging